### ISSUE TITLE
rename initial_data.json

### ISSUE THREAD

**Issue by MichalMaM** [ella/django-markup#4]
Please rename initial_data.json for something else such as  _initial_data.json. Becouse if we have custom text processor in our project in db and run django command syncdb so our custom text procesor will be replaced to default from initial_data.json

**Comment by honzakral** [comment]
And how did you get the custom processor in the DB in the first place? You should have added it on top of the existing records from the fixture that should have been there already. At least it should have different PK so that the fixture won't touch it.

As such this issue is invalid - the processors in initial_data should always be there for the app to work properly so inital_data is a correct place for them.
